services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Add this line
      MYSQL_DATABASE: kaddem
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    networks:
      - spring-network


volumes:
  mysql_data: {}

networks:
  spring-network:
    driver: bridge  # Explicitly use bridge networking
