version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent volume for MySQL data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Root password for MySQL
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Initial database to create
      MYSQL_USER: ${MYSQL_USER}                    # Application user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # Password for application user
    networks:
      - spring-network  # Isolated network for security and configuration

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus  # Persistent volume for Prometheus data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - spring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana  # Persistent volume for Grafana data
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}  # Set Grafana admin password
    networks:
      - spring-network

volumes:
  mysql_data: {}
  prometheus_data: {}
  grafana_data: {}

networks:
  spring-network:
    driver: bridge  # Explicitly use bridge networking
