services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kaddem
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    networks:
      - spring-network

  app-kaddem:
    image: mayahinasr/spring-app
    container_name: app-kaddem
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true",
        "spring.datasource.username": "springuser",
        "spring.datasource.password": "springpass",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "server.servlet.context-path": "/kaddem",
        "server.port": "8089"
      }'
    networks:
      - spring-network
    stdin_open: true
    tty: true

networks:
  spring-network:
    driver: bridge  # Explicitly use bridge networking

volumes:
  mysql_data:
