services:
  spring-app:
    build: .
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8096:8096"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network

volumes:
  mysql_data: {}

networks:
  spring-network:
    driver: bridge
