services:
  spring-app:
    build: .
    networks:
      - spring-network
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8096:8096"
    restart: always


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password here
      MYSQL_DATABASE: kaddem
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 20s
      retries: 5
    networks:
      - spring-network



volumes:
  mysql_data: {}

networks:
  spring-network:
    driver: bridge
