version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass


volumes:
  mysql_data: {}

networks:
  default:
    name: mysql_network
