services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    networks:
      - spring-network

  spring-app:
    image: spring-app:latest  # Use the locally built image name
    container_name: spring-app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springpass
    depends_on:
      - mysql
    networks:
      - spring-network

volumes:
  mysql_data: {}

networks:
  spring-network:
    driver: bridge
